### ISSUE TITLE
gen_indoor3d_h5.py--error

### ISSUE THREAD

**Issue by Chengyuelan** [y2kmz/pointnetv2#1]
When I made the H5 data set, I encountered a problem. How do I solve it? I will be very grateful if I receive your reply.
@y2kmz 
Traceback (most recent call last):
  File "gen_indoor3d_h5.py", line 83, in <module>
    insert_batch(data, label, i == len(data_label_files))
  File "gen_indoor3d_h5.py", line 58, in insert_batch
    data_prep_util.save_h5(h5_filename, h5_batch_data, h5_batch_label, data_dtype, label_dtype)
  File "/home/pointnetv2-master/utils/data_prep_util.py", line 80, in save_h5
    h5_fout = h5py.File(h5_filename)
  File "/home/anaconda3/envs/pointnetv2/lib/python3.7/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/anaconda3/envs/pointnetv2/lib/python3.7/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/home/pointnetv2-master/data/indoor3d_sem_seg_hdf5_a_all_0.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by y2kmz** [comment]
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/home/pointnetv2-master/data/indoor3d_sem_seg_hdf5_a_all_0.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

It seems you set a wrong path of .h5 file.
fix the path and try again?
